### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [hetznerZA/hetzner-filebeats#44]
Hello,
I see no license mentioned anywhere, which license does apply to this project?
Regards

**Comment by shaunbugler** [comment]
Hi @lavalampa we use Apache v2.0, I will update the project with the license. thanks for bringing this to our attention

**Comment by shaunbugler** [comment]
apache2 2.0 license added in release [2.1.1](https://github.com/xneelo/hetzner-filebeats/tree/2.1.1)
