### ISSUE TITLE
Redhat / Centos Support

### ISSUE THREAD

**Issue by mativillagra** [hetznerZA/hetzner-filebeats#5]
Hello! 

Let me ask if you plan to add Centos / Redhat support for this module. 

Thanks in advance.

**Comment by shaunbugler** [comment]
Hi @mativillagra we currently only run filebeats on Debian, so we don't have a base to really test or develop on. I don't think the changes would be too big, maybe give it a go and we can help?

**Comment by czhujer** [comment]
Which version of CentOS do you need? I have tested module with centos 6.. https://github.com/SugarFactory/puppet-beats

**Comment by JoshuaSmeda** [comment]
Closing issue due to stagnation and above repository no longer active.
